#use_frameworks!

target 'CHUncaughtExceptionHandler_Example' do
  pod 'CHUncaughtExceptionHandler', :path => '../'

  target 'CHUncaughtExceptionHandler_Tests' do
    inherit! :search_paths

    
  end
end
